name: Setup
description: Install pnpm, Node.js, and dependencies

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v5

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install
